# Generated by Django 5.0.2 on 2024-03-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysheet', '0005_staycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
